name: bmp-rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - samtools=1.20
  - bcftools=1.20
  - bedtools=2.31
  - fastqc=0.12
  - fastp=0.23
  - salmon=1.10
  - multiqc=1.21